shipbot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100

  # Position Controllers ---------------------------------------
  shoulder1_controller:
    type: position_controllers/JointPositionController
    joint: shoulder1
    pid: {p: 3.0, i: 0.0, d: 0.0}

  shoulder2_controller:
    type: position_controllers/JointPositionController
    joint: shoulder2
    pid: {p: 3.0, i: 0.0, d: 0.0}

  elbow_controller:
    type: position_controllers/JointPositionController
    joint: elbow
    pid: {p: 3.0, i: 0.0, d: 0.0}

  wrist1_controller:
    type: position_controllers/JointPositionController
    joint: wrist1
    pid: {p: 3.0, i: 0.0, d: 0.0}

  wrist2_controller:
    type: position_controllers/JointPositionController
    joint: wrist2
    pid: {p: 3.0, i: 0.0, d: 0.0}
